import base64
import json
import re
import httpx

GITHUB_API = "https://api.github.com"


def _headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9\-_.]", "-", name).strip("-")
    return slug[:100] or "project"


async def create_repo(token: str, name: str, description: str = "") -> dict:
    slug = _slugify(name)
    async with httpx.AsyncClient(timeout=20) as client:
        res = await client.post(
            f"{GITHUB_API}/user/repos",
            headers=_headers(token),
            json={"name": slug, "description": description, "private": True, "auto_init": True},
        )
        if res.status_code == 422:
            # Repo already exists — fetch it
            me = await client.get(f"{GITHUB_API}/user", headers=_headers(token))
            username = me.json()["login"]
            existing = await client.get(f"{GITHUB_API}/repos/{username}/{slug}", headers=_headers(token))
            return {"name": slug, "html_url": existing.json()["html_url"], "full_name": existing.json()["full_name"]}
        res.raise_for_status()
        data = res.json()
        return {"name": slug, "html_url": data["html_url"], "full_name": data["full_name"]}


async def push_files(token: str, full_name: str, files: dict, commit_message: str = "Update from Text Dev IDE") -> None:
    """Push multiple files to a repo. files = {path: content_str}"""
    async with httpx.AsyncClient(timeout=30) as client:
        for path, content in files.items():
            encoded = base64.b64encode(content.encode()).decode()
            # Check if file exists to get its SHA
            check = await client.get(f"{GITHUB_API}/repos/{full_name}/contents/{path}", headers=_headers(token))
            sha = check.json().get("sha") if check.status_code == 200 else None
            payload = {"message": commit_message, "content": encoded}
            if sha:
                payload["sha"] = sha
            await client.put(
                f"{GITHUB_API}/repos/{full_name}/contents/{path}",
                headers=_headers(token),
                json=payload,
            )


def build_push_files(project) -> tuple:
    """
    Build files following the repo structure:

    root
    ├── README.md
    ├── meta-data/
    │   ├── schema/          ← database table XML (one per table, e.g. Course.xml)
    │   ├── ui/              ← screen XML definitions (one per screen)
    │   └── validations/     ← validation rules text
    └── deployment/
        ├── db-design/       ← SQL files (one per table, e.g. Course.sql)
        ├── html/            ← generated HTML screens
        ├── API/             ← generated API code per screen
        └── common-library/  ← validation/entity code (Python/Java/etc)
    """
    files = {}
    ext = {"Python": "py", "Java": "java", "JavaScript": "js", "TypeScript": "ts",
           "C#": "cs", "Go": "go", "Ruby": "rb", "PHP": "php"}.get(project.language, "txt")

    # README
    readme = f"# {project.name}\n\n"
    if project.description:
        readme += f"{project.description}\n\n"
    readme += f"**Language:** {project.language}\n\n"
    readme += "## Structure\n"
    readme += "- `meta-data/schema/` — database table XML definitions (one per table)\n"
    readme += "- `meta-data/ui/` — screen XML definitions (one per screen)\n"
    readme += "- `meta-data/validations/` — validation rules\n"
    readme += "- `deployment/db-design/` — SQL files (one per table)\n"
    readme += "- `deployment/html/` — generated HTML screens\n"
    readme += "- `deployment/API/` — generated REST API code\n"
    readme += f"- `deployment/common-library/` — entity/validation code ({project.language})\n\n"
    readme += "_Generated by [Text Dev IDE](https://textdevide.netlify.app)_\n"
    files["README.md"] = readme

    # meta-data/validations/
    if project.validation_rules:
        files["meta-data/validations/rules.md"] = f"# Validation Rules\n\n{project.validation_rules}\n"

    # deployment/common-library/ — entity + validation code
    if project.validation_code:
        files[f"deployment/common-library/validation.{ext}"] = project.validation_code

    # meta-data/schema/ — one XML per database table (entity structure)
    # deployment/db-design/ — one SQL file per table
    if project.entities:
        try:
            entities = json.loads(project.entities)
            for table in entities.get("tables", []):
                tname = table["name"]

                # Entity XML
                xml_lines = [f'<?xml version="1.0" encoding="UTF-8"?>',
                             f'<entity name="{tname}">',
                             '  <columns>']
                for col in table.get("columns", []):
                    pk = str(col.get("pk", False)).lower()
                    fk = col.get("fk") or "null"
                    xml_lines.append(
                        f'    <column name="{col["name"]}" type="{col.get("type","VARCHAR")}" pk="{pk}" fk="{fk}"/>'
                    )
                xml_lines += ['  </columns>', '</entity>']
                files[f"meta-data/schema/{tname}.xml"] = "\n".join(xml_lines)

                # Individual SQL file
                cols = []
                fk_constraints = []
                for col in table.get("columns", []):
                    col_type = col.get("type", "VARCHAR(255)")
                    pk = " PRIMARY KEY" if col.get("pk") else ""
                    cols.append(f"  {col['name']} {col_type}{pk}")
                    if col.get("fk"):
                        ref_table, ref_col = (col["fk"].split(".") + ["id"])[:2]
                        fk_constraints.append(
                            f"  FOREIGN KEY ({col['name']}) REFERENCES {ref_table}({ref_col})"
                        )
                all_cols = cols + fk_constraints
                sql = f"-- {tname} table\nCREATE TABLE IF NOT EXISTS {tname} (\n" + ",\n".join(all_cols) + "\n);\n"
                files[f"deployment/db-design/{tname}.sql"] = sql
        except Exception:
            pass

    # screens
    screen_names = []
    if project.ui_screens:
        try:
            screens = json.loads(project.ui_screens)
            for screen in screens:
                slug = re.sub(r"[^a-zA-Z0-9_\-]", "_", screen.get("name", "screen"))
                screen_names.append(screen.get("name", slug))

                # meta-data/ui/ — screen XML definition
                if screen.get("xml"):
                    files[f"meta-data/ui/{slug}.xml"] = screen["xml"]

                # deployment/html/
                if screen.get("html"):
                    files[f"deployment/html/{slug}.html"] = screen["html"]

                # deployment/API/
                if screen.get("api"):
                    files[f"deployment/API/{slug}.{ext}"] = screen["api"]
        except Exception:
            pass

    return files, screen_names


def build_commit_message(project, screen_names: list) -> str:
    parts = []
    if project.validation_code:
        parts.append("validation code")
    if screen_names:
        names = ", ".join(screen_names[:3])
        suffix = f" +{len(screen_names) - 3} more" if len(screen_names) > 3 else ""
        parts.append(f"{len(screen_names)} screen{'s' if len(screen_names) > 1 else ''}: {names}{suffix}")
    body = " and ".join(parts) if parts else "project files"
    return f"Update {body}"
