"""Backs the Studio's UI Preview with real rows in a real Postgres schema, instead of the
fake sampleData baked into generated HTML or the browser-only mock store. Each project gets
its own Postgres schema (proj_<id>) with tables created/kept in sync with project.entities.

This is a testing/preview aid, not the app's real generated backend (that's a separate,
static source-code deliverable in the Backend Code tab) — so it deliberately keeps things
simple: a "replace all rows" sync per entity rather than a full incremental CRUD/diff API,
no autonumber sequence or formula-trigger enforcement at the DB level. Good enough to let
someone add data in one screen's preview and see it for real in another.
"""
import logging
import re
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_TYPE_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*(\(\s*\d+\s*(,\s*\d+\s*)?\))?$")


def _safe_ident(name: str) -> str:
    if not name or not _IDENT_RE.match(name):
        raise ValueError(f"Unsafe identifier: {name!r}")
    return name


def _safe_type(sql_type: str) -> str:
    t = (sql_type or "TEXT").strip()
    if not _TYPE_RE.match(t):
        return "TEXT"  # unrecognized/unsafe type string — fall back rather than reject the whole sync
    return t


def _default_clause(ctype: str) -> str:
    """Mirrors the CURRENT_TIMESTAMP convention _generate_sql_schema uses for the real generated
    backend (ai_service.py) — a TIMESTAMP column (createdAt/modifiedAt-style audit fields) should
    auto-fill itself at the DB level, since a plain HTML/JS preview form never asks the user to
    type one in."""
    return " DEFAULT CURRENT_TIMESTAMP" if ctype.upper().startswith("TIMESTAMP") else ""


_INTEGER_TYPES = {"INT", "INTEGER", "SMALLINT", "BIGINT"}


def _pk_identity_clause(col: dict, ctype: str) -> str:
    """A plain surrogate integer "id" primary key (pk=true, autonumber=null — the schema rules'
    own distinction from a formatted/business-key autonumber like deptid) is meant to be system-
    generated and is correctly never shown on the form (the metadata generator hides pk fields).
    But a plain HTML/JS preview grid can't supply a value for it either, so without this the
    column's own NOT NULL constraint fails every single insert. GENERATED BY DEFAULT AS IDENTITY
    (not ALWAYS) still lets an explicit id through if one's ever provided, matching SERIAL-like
    auto-increment semantics."""
    if col.get("pk") and not col.get("autonumber") and ctype.upper() in _INTEGER_TYPES:
        return " GENERATED BY DEFAULT AS IDENTITY"
    return ""


_AUDIT_COLUMN_NAMES = {"createdby", "modifiedby", "updatedby", "created_by", "modified_by", "updated_by"}


def schema_name(project_id: int) -> str:
    return f"proj_{project_id}"


async def _try_execute(conn: AsyncSession, sql: str, params: dict | None = None) -> bool:
    """Runs one statement inside its own SAVEPOINT. Postgres aborts the *entire* surrounding
    transaction the instant any statement fails — a plain try/except around conn.execute()
    does not recover from that, every later statement in the same transaction would also fail
    with "current transaction is aborted" even though it has nothing to do with the original
    error. A savepoint scopes the rollback to just this one statement."""
    try:
        async with conn.begin_nested():
            await conn.execute(text(sql), params or {})
        return True
    except Exception as e:
        logger.warning("preview_db statement failed, rolled back to savepoint: %s | sql=%s | params=%s", e, sql, params)
        return False


async def sync_schema(conn: AsyncSession, project_id: int, entities: dict) -> None:
    """Creates the project's Postgres schema and tables if missing, and ALTERs in any new
    columns for tables that already exist — mirrors _add_missing_columns' drift-bridging
    approach in app/database.py, just scoped to one project's dynamic schema instead of the
    app's own fixed models."""
    schema = schema_name(project_id)
    await _try_execute(conn, f'CREATE SCHEMA IF NOT EXISTS "{schema}"')

    tables = entities.get("tables", [])
    valid_tables = []
    for table in tables:
        try:
            tname = _safe_ident(table["name"])
        except ValueError:
            continue
        columns = table.get("columns", [])
        if not columns:
            continue
        valid_tables.append((tname, table))

        col_defs = []
        pk_cols = []
        for col in columns:
            try:
                cname = _safe_ident(col["name"])
            except ValueError:
                continue
            ctype = _safe_type(col.get("type", "TEXT"))
            nullable = "" if col.get("nullable", True) else " NOT NULL"
            col_defs.append(f'"{cname}" {ctype}{_default_clause(ctype)}{_pk_identity_clause(col, ctype)}{nullable}')
            if col.get("pk"):
                pk_cols.append(cname)
        if not col_defs:
            continue
        pk_quoted = ", ".join(f'"{c}"' for c in pk_cols)
        pk_clause = f", PRIMARY KEY ({pk_quoted})" if pk_cols else ""
        ddl = f'CREATE TABLE IF NOT EXISTS "{schema}"."{tname}" ({", ".join(col_defs)}{pk_clause})'
        if not await _try_execute(conn, ddl):
            continue

        # Bridge drift: add any columns that are new since this table was first created, and
        # pick up nullable changes made afterward (e.g. via the Schema Assistant) on columns
        # that already exist — CREATE TABLE IF NOT EXISTS never touches an existing table, so
        # without this a column's NOT NULL can go stale and keep rejecting inserts the schema
        # no longer actually requires.
        existing = await conn.execute(text(
            "SELECT column_name, is_nullable FROM information_schema.columns WHERE table_schema = :s AND table_name = :t"
        ), {"s": schema, "t": tname})
        existing_cols = {r[0]: r[1] == "YES" for r in existing.fetchall()}
        for col in columns:
            try:
                cname = _safe_ident(col["name"])
            except ValueError:
                continue
            wants_nullable = col.get("nullable", True)
            if cname not in existing_cols:
                ctype = _safe_type(col.get("type", "TEXT"))
                await _try_execute(conn, f'ALTER TABLE "{schema}"."{tname}" ADD COLUMN "{cname}" {ctype}{_default_clause(ctype)}')
            elif existing_cols[cname] != wants_nullable:
                clause = "DROP NOT NULL" if wants_nullable else "SET NOT NULL"
                await _try_execute(conn, f'ALTER TABLE "{schema}"."{tname}" ALTER COLUMN "{cname}" {clause}')

    # Foreign keys as a second pass so tables can reference each other regardless of order.
    for tname, table in valid_tables:
        for col in table.get("columns", []):
            fk = col.get("fk")
            if not fk or "." not in fk:
                continue
            try:
                cname = _safe_ident(col["name"])
                ref_table, ref_col = fk.split(".", 1)
                ref_table = _safe_ident(ref_table)
                ref_col = _safe_ident(ref_col)
            except ValueError:
                continue
            constraint = f"fk_{tname}_{cname}"[:63]
            ddl = (
                f'ALTER TABLE "{schema}"."{tname}" ADD CONSTRAINT "{constraint}" '
                f'FOREIGN KEY ("{cname}") REFERENCES "{schema}"."{ref_table}" ("{ref_col}")'
            )
            await _try_execute(conn, ddl)  # fails silently if it already exists — that's fine


def _find_table(entities: dict, entity: str) -> dict | None:
    return next((t for t in entities.get("tables", []) if t.get("name") == entity), None)


async def list_rows(conn: AsyncSession, project_id: int, entities: dict, entity: str) -> list[dict]:
    table = _find_table(entities, entity)
    if not table:
        return []
    schema = schema_name(project_id)
    tname = _safe_ident(entity)
    result = await conn.execute(text(f'SELECT * FROM "{schema}"."{tname}" LIMIT 500'))
    return [dict(row._mapping) for row in result.fetchall()]


def _coerce_value(value, sql_type: str):
    """asyncpg (unlike psycopg2) binds parameters by Python type, not by casting strings — a
    DATE/TIMESTAMP/NUMERIC/BOOLEAN column needs a real date/datetime/Decimal/bool object, not the
    ISO string JSON hands us from a browser payload, or the insert fails with something like
    "'str' object has no attribute 'toordinal'". TEXT/INT columns pass through unchanged since
    asyncpg parses plain ints/strings fine."""
    if not isinstance(value, str):
        return value
    t = (sql_type or "").strip().upper()
    try:
        if t.startswith("TIMESTAMP"):
            return datetime.fromisoformat(value.replace("Z", "+00:00"))
        if t.startswith("DATE"):
            return date.fromisoformat(value[:10])
        if t.startswith("DECIMAL") or t.startswith("NUMERIC"):
            return Decimal(value)
        if t in ("BOOLEAN", "BOOL"):
            return value.strip().lower() in ("true", "1", "yes")
        if t in ("INT", "INTEGER", "SMALLINT", "BIGINT"):
            return int(value)
        if t in ("FLOAT", "REAL", "DOUBLE PRECISION"):
            return float(value)
    except (ValueError, InvalidOperation):
        return None  # unparsable for this column's type — drop rather than fail the whole row
    return value


def _format_autonumber(config: dict, n: int) -> str:
    prefix, suffix = config.get("prefix") or "", config.get("suffix") or ""
    try:
        width = int(config.get("leading_zeroes") or 0)
    except (TypeError, ValueError):
        width = 0
    digits = str(n).zfill(width) if width > len(str(n)) else str(n)
    return f"{prefix}{digits}{suffix}"


def _autonumber_seed(config: dict, existing_values: list) -> tuple[int, int]:
    """(next_n, step) seeded from the highest number already present among the incoming rows —
    so re-saving rows that already have a real autonumbered value never collides with a freshly
    generated one — falling back to the column's configured start_number when nothing exists yet."""
    prefix, suffix = config.get("prefix") or "", config.get("suffix") or ""
    try:
        step = int(config.get("step_number") or 1)
    except (TypeError, ValueError):
        step = 1
    try:
        start = int(config.get("start_number") or 1)
    except (TypeError, ValueError):
        start = 1
    pattern = re.compile("^" + re.escape(prefix) + r"(\d+)" + re.escape(suffix) + "$")
    seen_max = None
    for v in existing_values:
        m = pattern.match(str(v))
        if m:
            n = int(m.group(1))
            seen_max = n if seen_max is None else max(seen_max, n)
    next_n = (seen_max + step) if seen_max is not None else start
    return next_n, step


async def replace_all_rows(conn: AsyncSession, project_id: int, entities: dict, entity: str, rows: list[dict]) -> None:
    table = _find_table(entities, entity)
    if not table:
        raise ValueError(f"Unknown entity: {entity}")
    schema = schema_name(project_id)
    tname = _safe_ident(entity)
    columns = table.get("columns", [])
    col_types = {c["name"]: c.get("type", "TEXT") for c in columns}
    # NOT NULL audit columns (createdBy/modifiedBy/...) that TIMESTAMP defaults don't cover — a
    # plain HTML/JS preview grid never has the user type these in, so fill them in here rather
    # than failing the whole row's insert on a NOT NULL violation the grid could never satisfy.
    required_audit_cols = {
        c["name"] for c in columns
        if not c.get("nullable", True) and c["name"].lower() in _AUDIT_COLUMN_NAMES
    }
    # Autonumbered columns (e.g. deptid formatted like "d0009") are never typed by the user — the
    # form correctly never asks for one — so the row arrives with it missing on every genuine new
    # entry. Generate it here instead, seeded from the highest value already present in this same
    # batch so re-saving previously-autonumbered rows can never collide with a freshly minted one.
    autonumber_state = {}
    for c in columns:
        if not c.get("autonumber"):
            continue
        existing = [row.get(c["name"]) for row in rows if row.get(c["name"]) not in (None, "")]
        next_n, step = _autonumber_seed(c["autonumber"], existing)
        autonumber_state[c["name"]] = {"config": c["autonumber"], "next": next_n, "step": step}

    await _try_execute(conn, f'DELETE FROM "{schema}"."{tname}"')
    for row in rows:
        coerced = {k: _coerce_value(v, col_types[k]) for k, v in row.items() if k in col_types and v not in (None, "")}
        # A value that failed to coerce for its column's type (e.g. int("(auto)") on a scraped
        # placeholder) comes back as None from _coerce_value — omit it entirely rather than
        # sending an explicit NULL, so a NOT NULL column with no real default still fails with a
        # clear constraint error instead of silently forcing NULL through.
        data = {k: v for k, v in coerced.items() if v is not None}
        for c in required_audit_cols:
            data.setdefault(c, "preview")
        for cname, state in autonumber_state.items():
            if row.get(cname) in (None, ""):
                data[cname] = _format_autonumber(state["config"], state["next"])
                state["next"] += state["step"]
        if not data:
            continue
        cols = list(data.keys())
        try:
            for c in cols:
                _safe_ident(c)
        except ValueError:
            continue
        col_list = ", ".join(f'"{c}"' for c in cols)
        param_list = ", ".join(f":{c}" for c in cols)
        await _try_execute(conn, f'INSERT INTO "{schema}"."{tname}" ({col_list}) VALUES ({param_list})', data)
